.TH "LoadFileException" 3 "Tue Jan 11 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadFileException
.SH SYNOPSIS
.br
.PP
.PP
Inherits runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadFileException\fP (const std::string &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file LoadFileException\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
