.TH "logic::BGTile" 3 "Tue Jan 11 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::BGTile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogic::EntityModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBGTile\fP ()"
.br
.ti -1c
.RI "\fB~BGTile\fP () override=default"
.br
.ti -1c
.RI "\fBBGTile\fP (float posX, float posY)"
.br
.ti -1c
.RI "\fBBGTile\fP (float posX, float posY, float width, float height)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file BGTile\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "logic::BGTile::BGTile ()\fC [default]\fP"
@function : \fBBGTile\fP Constructor for a background tile\&. 
.SS "logic::BGTile::~BGTile ()\fC [override]\fP, \fC [default]\fP"
@function : \fBBGTile\fP Destructor for a background tile\&. 
.SS "logic::BGTile::BGTile (float posX, float posY)"
@function : \fBBGTile\fP Constructor for a background tile\&. 
.PP
\fBParameters\fP
.RS 4
\fIposX\fP (float) : x-coordinate of our entity, between the range [0,1-entity\&.width]\&. 
.br
\fIposY\fP (float) : y-coordinate of our entity, between the range [0+entity\&.height, inf[\&. 
.RE
.PP

.PP
Definition at line 9 of file BGTile\&.cpp\&.
.SS "logic::BGTile::BGTile (float posX, float posY, float width, float height)"
@function : \fBBGTile\fP Constructor for a background tile\&. 
.PP
\fBParameters\fP
.RS 4
\fIposX\fP (float) : x-coordinate of our entity, between the range [0,1-entity\&.width]\&. 
.br
\fIposY\fP (float) : y-coordinate of our entity, between the range [0+entity\&.height, inf[\&. 
.br
\fIwidth\fP (float) : width of our entity\&. 
.br
\fIheight\fP (float) : height of our entity\&. 
.RE
.PP

.PP
Definition at line 11 of file BGTile\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
