.TH "logic::Spring" 3 "Tue Jan 11 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::Spring
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogic::Bonus\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpring\fP ()"
.br
.ti -1c
.RI "\fB~Spring\fP () override=default"
.br
.ti -1c
.RI "\fBSpring\fP (float posX, float posY)"
.br
.ti -1c
.RI "\fBSpring\fP (float posX, float posY, float width, float height)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file Spring\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "logic::Spring::Spring ()\fC [default]\fP"
@function : \fBSpring\fP Constructor for a \fBSpring\fP\&. 
.SS "logic::Spring::~Spring ()\fC [override]\fP, \fC [default]\fP"
@function : \fBSpring\fP Destructor for a \fBSpring\fP\&. 
.SS "logic::Spring::Spring (float posX, float posY)"
@function : \fBSpring\fP Constructor for a \fBSpring\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIposX\fP (float) : x-coordinate of our entity, between the range [0,1-entity\&.width]\&. 
.br
\fIposY\fP (float) : y-coordinate of our entity, between the range [0+entity\&.height, inf[\&. 
.RE
.PP

.PP
Definition at line 9 of file Spring\&.cpp\&.
.SS "logic::Spring::Spring (float posX, float posY, float width, float height)"
@function : \fBSpring\fP Constructor for a \fBSpring\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIposX\fP (float) : x-coordinate of our entity, between the range [0,1-entity\&.width]\&. 
.br
\fIposY\fP (float) : y-coordinate of our entity, between the range [0+entity\&.height, inf[\&. 
.br
\fIwidth\fP (float) : width of our entity\&. 
.br
\fIheight\fP (float) : height of our entity\&. 
.RE
.PP

.PP
Definition at line 16 of file Spring\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
