.TH "logic::Jetpack" 3 "Tue Jan 11 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::Jetpack
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogic::Bonus\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJetpack\fP ()"
.br
.ti -1c
.RI "\fB~Jetpack\fP () override=default"
.br
.ti -1c
.RI "\fBJetpack\fP (float posX, float posY)"
.br
.ti -1c
.RI "\fBJetpack\fP (float posX, float posY, float width, float height)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file Jetpack\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "logic::Jetpack::Jetpack ()\fC [default]\fP"
@function : \fBJetpack\fP Constructor for a \fBJetpack\fP\&. 
.SS "logic::Jetpack::~Jetpack ()\fC [override]\fP, \fC [default]\fP"
@function : \fBJetpack\fP Destructor for a \fBJetpack\fP\&. 
.SS "logic::Jetpack::Jetpack (float posX, float posY)"
@function : \fBJetpack\fP Constructor for a \fBJetpack\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIposX\fP (float) : x-coordinate of our entity, between the range [0,1-entity\&.width]\&. 
.br
\fIposY\fP (float) : y-coordinate of our entity, between the range [0+entity\&.height, inf[\&. 
.RE
.PP

.PP
Definition at line 9 of file Jetpack\&.cpp\&.
.SS "logic::Jetpack::Jetpack (float posX, float posY, float width, float height)"
@function : \fBJetpack\fP Constructor for a \fBJetpack\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIposX\fP (float) : x-coordinate of our entity, between the range [0,1-entity\&.width]\&. 
.br
\fIposY\fP (float) : y-coordinate of our entity, between the range [0+entity\&.height, inf[\&. 
.br
\fIwidth\fP (float) : width of our entity\&. 
.br
\fIheight\fP (float) : height of our entity\&. 
.RE
.PP

.PP
Definition at line 16 of file Jetpack\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
