.TH "representation::BGTile_GR" 3 "Tue Jan 11 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
representation::BGTile_GR
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrepresentation::EntityView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBGTile_GR\fP (const std::shared_ptr< \fBlogic::EntityModel\fP > &entityModel)"
.br
.ti -1c
.RI "\fB~BGTile_GR\fP () override=default"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file BGTile_GR\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "representation::BGTile_GR::BGTile_GR (const std::shared_ptr< \fBlogic::EntityModel\fP > & entityModel)"
@function : \fBBGTile_GR\fP Constructor for a \fBBGTile_GR\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIentityModel\fP (std::shared_ptr<logic::EntityModel>) : entityModel 
.RE
.PP

.PP
Definition at line 7 of file BGTile_GR\&.cpp\&.
.SS "representation::BGTile_GR::~BGTile_GR ()\fC [override]\fP, \fC [default]\fP"
@function : \fBBGTile_GR\fP Destructor for a \fBBGTile_GR\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
