.TH "representation::Bonus_GR" 3 "Tue Jan 11 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
representation::Bonus_GR
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrepresentation::EntityView\fP\&.
.PP
Inherited by \fBrepresentation::Jetpack_GR\fP, and \fBrepresentation::Spring_GR\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBonus_GR\fP ()"
.br
.ti -1c
.RI "\fB~Bonus_GR\fP () override=default"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file Bonus_GR\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "representation::Bonus_GR::Bonus_GR ()\fC [default]\fP"
@function : \fBBonus_GR\fP Constructor for a \fBBonus_GR\fP\&. 
.SS "representation::Bonus_GR::~Bonus_GR ()\fC [override]\fP, \fC [default]\fP"
@function : \fBBonus_GR\fP Destructor for a \fBBonus_GR\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
