.TH "representation::Spring_GR" 3 "Tue Jan 11 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
representation::Spring_GR
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrepresentation::Bonus_GR\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpring_GR\fP (const std::shared_ptr< \fBlogic::EntityModel\fP > &entityModel)"
.br
.ti -1c
.RI "\fB~Spring_GR\fP () override=default"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file Spring_GR\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "representation::Spring_GR::Spring_GR (const std::shared_ptr< \fBlogic::EntityModel\fP > & entityModel)"
@function : \fBSpring_GR\fP Constructor for a \fBSpring_GR\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIentityModel\fP (std::shared_ptr<logic::EntityModel>) : entityModel 
.RE
.PP

.PP
Definition at line 7 of file Spring_GR\&.cpp\&.
.SS "representation::Spring_GR::~Spring_GR ()\fC [override]\fP, \fC [default]\fP"
@function : \fBSpring_GR\fP Destructor for a \fBSpring_GR\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
